config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root 'tasks#index'

  devise_for :users

  resources :tasks do
    member do
      put :complete
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
require 'csv'

class Event < ApplicationRecord
  belongs_to :task

  validates :event_type, presence: true
  validates :payload, presence: true

  def self.to_csv(options = {})
    CSV.generate(options) do |csv_file|
      csv_file << csv_header_row

      all.each do |event|
        csv_file << [ event.payload['user_email'],
                      event.payload['colour'],
                      event.payload['phrase'],
                      event.payload['completed_at'] ]
      end
    end
  end

  def self.csv_header_row
    %w(UserEmail Colour Phrase Completed_at)
  end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if:  :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :complete]
  before_action :authenticate_user!

  def index
    @tasks = current_user.tasks
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_path, notice: 'Task was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: 'Task was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
    end
  end

  def complete
    @task.update_attribute(:completed, true)
    TrackingEventWorker.perform_async(@task.id) 

    respond_to do |format|
      format.html { redirect_to tasks_path, notice: "Task #{@task.title} was successfully completed." }
    end
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :completed)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <%= value %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WorldPackers To-Do App</a>
    </div>
    <ul class="nav navbar-nav mr-auto">
      <li class="nav-item active>"><a href="<%= tasks_path%>" class="nav-link">Tasks</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="nav-item active"><%= link_to current_user.email, edit_user_registration_path, class:  "nav-link"%></li>
        <li class="nav-item active"><%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item active"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link glyphicon glyphicon-user" %></li>
        <li class="nav-item active"><%= link_to "Login", new_user_session_path, class: "nav-link glyphicon glyphicon-log-in" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= render "layouts/messages"%>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
    <br>
    <%= form.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<div class="container mt-3">
  <div class="page-header">
    <h2>Editing Task</h2>
  </div>
</div>

<div class="container">
  <%= render 'form', task: @task %>
  <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/index.html.erb
<div class="container mt-3">
  <div class="page-header">
    <h2>Tasks</h2>
  </div>
</div>

<div class="container">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Completed?</th>
        <th>Created at</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.title %></td>
          <td><%= task.completed %></td>
          <td><%= task.created_at.strftime('%d/%m/%Y -  %H:%M:%S') %></td>
          <td>
            <%= link_to 'Show', task, class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Edit', edit_task_path(task), class: 'btn btn-primary btn-sm'  %>
            <%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
            <% unless task.completed %>
              <%= link_to 'Complete', complete_task_path(task), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-success btn-sm'  %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody> 
  </table>

  <br>

  <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
</div>

app/views/tasks/new.html.erb
<div class="container mt-3">
  <div class="page-header">
    <h2>New Task</h2>
  </div>
</div>

<div class="container">
  <%= render 'form', task: @task %>
  <%= link_to 'Back', tasks_path %>
</div>

app/views/tasks/show.html.erb
<div class="container mt-3">
  <div class="page-header">
    <h2>
      <strong>Title:</strong>
      <%= @task.title %>
    </h2>
    <p>
    <strong>Completed:</strong>
    <%= @task.completed %>
    </p>
  </div>
</div>


<div class="container">
  <%= link_to 'Edit', edit_task_path(@task) %>
</div>